mode: single
blueprint:
  name: IKEA BILRESA Dual Button
  author: Skaronator
  description: >
    Full-featured automation for the IKEA BILRESA dual-button remote.
    Supports single press, double press, and long press for both buttons.
    Version 1.0.0
  domain: automation
  source_url: https://raw.githubusercontent.com/Skaronator/home-assistant-blueprints/refs/heads/main/automation/ikea-bilresa-dual-button.yaml
  homeassistant:
    min_version: 2025.12.0

  input:
    button1_event:
      name: Button 1 – Event Entity
      description: >
        Select the event entity for Button 1
      selector:
        entity:
          filter:
            integration: matter
            domain: event
            device_class: button

    button2_event:
      name: Button 2 – Event Entity
      description: >
        Select the event entity for Button 2
      selector:
        entity:
          filter:
            integration: matter
            domain: event
            device_class: button

    # ---------------------------------------------------------------
    # BUTTON 1 ACTIONS
    # ---------------------------------------------------------------

    button1_single:
      name: Button 1 – Single Press
      description: Action for Button 1 single press (multi_press_1).
      default: []
      selector:
        action: {}

    button1_double:
      name: Button 1 – Double Press
      description: Action for Button 1 double press (multi_press_2).
      default: []
      selector:
        action: {}

    button1_long_press:
      name: Button 1 – Long Press (on press)
      description: Action for Button 1 long press completion (long_press).
      default: []
      selector:
        action: {}

    button1_long_release:
      name: Button 1 – Long Press (on release)
      description: Action for Button 1 long press completion (long_release).
      default: []
      selector:
        action: {}

    # ---------------------------------------------------------------
    # BUTTON 2 ACTIONS
    # ---------------------------------------------------------------

    button2_single:
      name: Button 2 – Single Press
      description: Action for Button 2 single press (multi_press_1).
      default: []
      selector:
        action: {}

    button2_double:
      name: Button 2 – Double Press
      description: Action for Button 2 double press (multi_press_2).
      default: []
      selector:
        action: {}

    button2_long_press:
      name: Button 2 – Long Press (on press)
      description: Action for Button 2 long press completion (long_press).
      default: []
      selector:
        action: {}

    button2_long_release:
      name: Button 2 – Long Press (on release)
      description: Action for Button 2 long press completion (long_release).
      default: []
      selector:
        action: {}

# ===================================================================
# AUTOMATION LOGIC
# ===================================================================

variables:
  button1_entity: !input button1_event
  button2_entity: !input button2_event

trigger:
  - platform: state
    id: button1
    entity_id: !input button1_event
  - platform: state
    id: button2
    entity_id: !input button2_event

condition: []

action:
  - variables:
      trigger_id: "{{ trigger.id }}"
      press_type: "{{ trigger.to_state.attributes.event_type }}"

  - choose:
      # -------------------------------------------------------------
      # BUTTON 1
      # -------------------------------------------------------------

      - conditions:
          - condition: template
            value_template: >
              {{ trigger_id == 'button1' and press_type == 'multi_press_1' }}
        sequence: !input button1_single

      - conditions:
          - condition: template
            value_template: >
              {{ trigger_id == 'button1' and press_type == 'multi_press_2' }}
        sequence: !input button1_double

      - conditions:
          - condition: template
            value_template: >
              {{ trigger_id == 'button1' and press_type == 'long_press' }}
        sequence: !input button1_long_press

      - conditions:
          - condition: template
            value_template: >
              {{ trigger_id == 'button1' and press_type == 'long_release' }}
        sequence: !input button1_long_release

      # -------------------------------------------------------------
      # BUTTON 2
      # -------------------------------------------------------------

      - conditions:
          - condition: template
            value_template: >
              {{ trigger_id == 'button2' and press_type == 'multi_press_1' }}
        sequence: !input button2_single

      - conditions:
          - condition: template
            value_template: >
              {{ trigger_id == 'button2' and press_type == 'multi_press_2' }}
        sequence: !input button2_double

      - conditions:
          - condition: template
            value_template: >
              {{ trigger_id == 'button2' and press_type == 'long_press' }}
        sequence: !input button2_long_press

      - conditions:
          - condition: template
            value_template: >
              {{ trigger_id == 'button2' and press_type == 'long_release' }}
        sequence: !input button2_long_release
